---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-binding
subjects:
- kind: ServiceAccount
  name: admin
  namespace: default
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: admin
spec:
  template:
    metadata:
      labels:
        kind: admin
    spec:
      serviceAccountName: admin
      restartPolicy: OnFailure
      containers:
      - name: test
        image: kubectl:local
        command:
        - sh
        - /tmp/check-kube-permissions.sh

        volumeMounts:
        - name: scripts
          mountPath: /tmp/check-kube-permissions.sh
          subPath: check-kube-permissions.sh

      volumes:
      - name: scripts
        configMap:
          name: scripts
